### ISSUE TITLE
Is CatCrypto still actively maintained?

### ISSUE THREAD

**Issue by palladionIT** [ImKcat/CatCrypto#14]
## Issue type

- [ ] Bug
- [ ] Feature
- [x] Question

## Desciption

Hello,

first of all, thank you for your OS contribution by providing this library. I am currently considering a few options to add `argon2` support to one of my react native projects and was wondering CatCrypto is still maintained? Seeing that this is a very important and security relevant project I want to get the project right from the beginning. I would really like to use CatCrypto but before I go ahead I wanted to confirm that this project is still actively maintained and reactive to CVE's etc.

Thank you!

**Comment by imkcat** [comment]
Hi @palladionIT!

First of all, I appreciate that you like this project. However, please note that it is not currently being actively maintained. Nonetheless, I may update it to support the latest Xcode and Apple platforms in the near future. Additionally, the crypto sources will be updated to the latest version if necessary with each release to address any CVE concerns.

And due to my busy schedule with other work, I cannot guarantee an exact update time. However, I will take a look at it this weekend. Additionally, this project welcomes pull requests.

**Comment by palladionIT** [comment]
Thank you very much! I appreciate the transparency.
