### ISSUE TITLE
Argon2 result with \0 at the end

### ISSUE THREAD

**Issue by SimonasA** [ImKcat/CatCrypto#4]
## Issue type

- [ ] Bug
- [ ] Feature
- [X] Question

## Before question

- [x] Reading [usage](https://github.com/ImKcat/CatCrypto#usage) section and [API Reference](https://imkcat.github.io/CatCrypto/)
- [X] Searched in [issues](https://github.com/ImKcat/CatCrypto/issues) to find duplicated or related issues

## Desciption

After updating to 0.3.0 I noticed null char at the end of result string when using Argon2 hash function.

i.e.
Even when checking CatCrypto tests (ArgonTests.swift) I expect to get
>"$argon2i$v=19$m=4096,t=3,p=1$ODExM0FENzYtQjFENC00NzE0LUE1NjktQTkyMDMzNkYzRkI3$wJfIvpKfuE91unyYNwEfLyuaXhWS9XuTJOGaFbP7wOE"

and I get this instead:

>"$argon2i$v=19$m=4096,t=3,p=1$ODExM0FENzYtQjFENC00NzE0LUE1NjktQTkyMDMzNkYzRkI3$wJfIvpKfuE91unyYNwEfLyuaXhWS9XuTJOGaFbP7wOE\0"

Is that expected behaviour?

![arg](https://user-images.githubusercontent.com/3868554/46607611-43a81300-cb0a-11e8-94ad-3121a14b8316.png)

**Comment by ImKcat** [comment]
It is due to the different from `String(cString:, encoding:)` and `String(bytes:, encoding:)`.

You can check this: [Why does String's bytes: and cString: initializers give different results here?
](https://stackoverflow.com/questions/44570363/why-does-strings-bytes-and-cstring-initializers-give-different-results-here)

Before 0.3.0, there is only one string output way and the process depend on cryptos, the Argon2 hash string was handle with `String(cString:, encoding:)`, the `\0` at the end of raw bytes was **ignored**.

After 0.3.0, I added more value output ways: `Raw`, `Bool`, `String`,  `Hex` and `Base64`, the string value output was processed from raw bytes with `String(bytes:, encoding:)`, so the string is not terminated by the first `\0`.

**Comment by ImKcat** [comment]
@SimonasA Sure, it is should be

If you want to use filtered string, there have a quick snippet to solve that:

```swift

let string = result.stringValue().filter{ $0 != "\0" }

```

**Comment by SimonasA** [comment]
@ImKcat, I could 👍 

Just then I must be 100% that "\0" is never a valid char in the given string :)

**Comment by ImKcat** [comment]
Added in 4c3e6b389f80c3fb9d873e039b10cb69dbbde34e
